mvc-postgresql-demo/Models/Blog.cs
using System.Collections.Generic;
namespace mvc_postgresql_demo.Models
{
    public class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }

        public List<Post> Posts { get; set; }
    }
}

mvc-postgresql-demo/Models/Post.cs
namespace mvc_postgresql_demo.Models
{
    public class Post
    {
        public int PostId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }

        public int BlogId { get; set; }
        public Blog Blog { get; set; }
    }
}

mvc-postgresql-demo/ViewModels/BlogViewModel.cs
using PagedList.Core;
using mvc_postgresql_demo.Models;

namespace mvc_postgresql_demo.ViewModels
{
    public class BlogViewModel
    {
        public IPagedList<Blog> Blogs { get; set; }
    }

}

mvc-postgresql-demo/Controllers/AccountController.cs
using System.Collections.Generic;
using System.Security.Claims;
using System;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http.Authentication;
using Microsoft.AspNetCore.Authorization;

namespace mvc_postgresql_demo.Controllers
{
    [AllowAnonymous]
    public class AccountController : Controller
    {
        public async Task<IActionResult> Login(string returnUrl = null)
        {
            const string Issuer = "https://contoso.com/";
            var claims = new List<Claim>();
            claims.Add(new Claim(ClaimTypes.Name, "hong duc", ClaimValueTypes.String, Issuer));
            claims.Add(new Claim(ClaimTypes.Role, "Admin", ClaimValueTypes.String, Issuer));
            claims.Add(new Claim(ClaimTypes.Role, "NotAdmin", ClaimValueTypes.String, Issuer));
            var userIdentity = new ClaimsIdentity("SuperSecureLogin");
            userIdentity.AddClaims(claims);
            var userPrincipal = new ClaimsPrincipal(userIdentity);

            await HttpContext.Authentication.SignInAsync("Cookie", userPrincipal, new AuthenticationProperties
            {
                ExpiresUtc = DateTime.UtcNow.AddMinutes(20),
                IsPersistent = false,
                AllowRefresh = false
            });

            return RedirectToLocal(returnUrl);
        }

        public IActionResult Forbidden()
        {
            return View();
        }

        private IActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

mvc-postgresql-demo/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using mvc_postgresql_demo.DAO;
using mvc_postgresql_demo.Models;
using mvc_postgresql_demo.Setting;
using Microsoft.Extensions.Options;
using Microsoft.Extensions.Logging;
using mvc_postgresql_demo.ViewModels;
using PagedList.Core;

namespace mvc_postgresql_demo.Controllers
{
    public class BlogController : Controller
    {
        private IDAO<Blog> _blogDAO;
        private AppSettings _appSettings;
        // thêm Microsoft.Extensions.Logging namespace mới có
        private readonly ILogger<BlogController> _logger;

        //them
        public BlogController(IOptions<AppSettings> appSettings, ILogger<BlogController> logger, IDAO<Blog> blogDAO)
        {
            this._blogDAO = blogDAO;
            // this._appSettings = appSettings.Value;
            //them
            this._logger = logger;
        }

        public IActionResult Index(string sortOrder, string searchString, int? page)
        {
            ViewData["CurrentSortOrder"] = sortOrder;
            ViewData["BlogIdSort"] = String.IsNullOrEmpty(sortOrder) ? "BlogId_desc" : "";
            ViewData["UrlSort"] = sortOrder == "Url" ? "Url_desc" : "Url";
            if (searchString != null)
            {
                page = 1;
            }

            page = page == null || page <= 0 ? 1 : page;
            var pageSize = 10;
            var blogViewModel = new BlogViewModel();
            var blogs = this._blogDAO.GetMany(page.Value, pageSize, sortOrder);
            blogViewModel.Blogs = new StaticPagedList<Blog>(blogs, page.Value, pageSize, this._blogDAO.Count());
            // ViewData["ExampleConfig"] = this._appSettings.ExampleKey;
            this._logger.LogInformation("Index page say hello", new object[0]);
            return View(blogViewModel);
        }

        public IActionResult Detail(int id)
        {
            var blog = this._blogDAO.GetOne(b => b.BlogId == id);
            ViewData["Title"] = "Blog number " + id;
            return View(blog);
        }
    }
}

mvc-postgresql-demo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace mvc_postgresql_demo.Controllers
{

    public class HomeController : Controller
    {
        // [Authorize(Policy = "AdminOnly")]
        public IActionResult Index()
        {
            return View();
        }

        // [Authorize(Roles = "SuperAdmin")]
        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

mvc-postgresql-demo/ViewComponents/PostViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using mvc_postgresql_demo.DAO;
using mvc_postgresql_demo.Models;

namespace mvc_postgresql_demo.ViewComponents
{
    public class PostViewComponent : ViewComponent
    {
        private IDAO<Post> _postDAO;

        public PostViewComponent(IDAO<Post> postDAO)
        {
            this._postDAO = postDAO;
        }
        public async Task<IViewComponentResult> InvokeAsync(int blogId)
        {
            // ViewData["blogId"] = blogId;
            // var posts = this._postDAO.GetMany(p => p.BlogId == blogId);
            // return await Task.Run(() => View(posts));
            return null;
        }
    }
}

mvc-postgresql-demo/Views/Blog/Components/Post/Default.cshtml
@model IEnumerable<mvc_postgresql_demo.Models.Post>
<h3>Post của Blog số @ViewData["blogId"]</h3>

@if(Model.Count() > 0)
{
    <ul>
        @foreach(var post in Model)
        {
            <li>Post id: @post.PostId, Title: @post.Title</li>
        }
    </ul>
}
else
{
    <p>No post in this Blog</p>
}

mvc-postgresql-demo/Views/Blog/Detail.cshtml
@model mvc_postgresql_demo.Models.Blog

<h2>@ViewData["Title"]</h2>

<p>BLog ID: @Model.BlogId</p>
<p>BLog Url: @Model.Url</p>

@await Component.InvokeAsync("Post", new {blogId = Model.BlogId})

mvc-postgresql-demo/Views/Blog/Index.cshtml
@using PagedList.Core.Mvc

@model mvc_postgresql_demo.ViewModels.BlogViewModel

@{
    ViewData["Title"] = "Blog";
}

<h2>@ViewData["Title"]</h2>

<!--<p>@ViewData["ExampleConfig"]</p>-->

@if(Model.Blogs != null){

<table class="table"> 
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["BlogIdSort"]">BlogId</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["UrlSort"]">Url</a>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var blog in Model.Blogs)
        {
            <tr>
                <th scope="row"><a asp-area="" asp-controller="Blog" asp-action="Detail" asp-route-id="@blog.BlogId">@blog.BlogId</a></th>
                <td>@blog.Url</td>
            </tr>
        }
        
    </tbody>
</table>    
}


<pager class="pager-container" list="@Model.Blogs" options="@PagedListRenderOptions.TwitterBootstrapPager" asp-route-sortOrder="@ViewData["CurrentSortOrder"]" asp-action="Index" asp-controller="Blog" />

mvc-postgresql-demo/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

mvc-postgresql-demo/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

mvc-postgresql-demo/Views/Home/Index.cshtml
@using System.Security.Claims;
@{
    ViewData["Title"] = "Home Page";
}

@if(!User.Identities.Any(u => u.IsAuthenticated)){
    <h1>Hello World</h1>
}
else{
    <h1>Hello @User.Identities.First(u => u.IsAuthenticated && u.HasClaim(c => c.Type == ClaimTypes.Name)).FindFirst(ClaimTypes.Name).Value</h1>
}

mvc-postgresql-demo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mvc_postgresql_demo</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">mvc_postgresql_demo</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Blog" asp-action="Index">Blog</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - mvc_postgresql_demo</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>